version: '3.1'

services:
  be:
    container_name: be
    image: athens-db-fundamentals
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
      - adminer
    volumes:
      - ./backend:/app
    networks:
      - athens-db-network
    environment:
      FLASK_APP: main:app
      FLASK_DEBUG: 1
      PYTHONBUFFERED: 1
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
      PROJECT_ID: athens-db-fundamentals
      PORT: 5000
      ENVIRONMENT: local

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: local
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - local-db:/var/lib/mysql
    networks:
      - athens-db-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  athens-db-network:
    driver: bridge

volumes:
  local-db: