version: '3.1'

services:
  fe:
    container_name: fe
    image: athens-db-fundamentals-fe
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    command: yarn start
    volumes:
      - ./frontend:/app
    depends_on:
      - be
    links:
      - be

  be:
    container_name: be
    image: athens-db-fundamentals-be
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    expose:
      - '5000'
    depends_on:
      - db
      - adminer
    volumes:
      - ./backend:/app
    # networks:
    #   - athens-db-network
    environment:
      FLASK_APP: main:app
      FLASK_DEBUG: 1
      PYTHONBUFFERED: 1
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: local
      PROJECT_ID: athens-db-fundamentals
      PORT: 5000
      ENVIRONMENT: local

  db:
    # image: mysql:5.7.22
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_USER: local
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: local
      MYSQL_PASSWORD: local
    volumes:
      - ./local-db:/var/lib/mysql
    # networks:
    #   - athens-db-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

# networks:
#   athens-db-network:
#     driver: bridge

volumes:
  local-db: